-- FWD Curated GIF Library — 400+ popular GIFs seeded as system content
-- owner_user_id = NULL → system/curated GIFs (show in Discover, Search, Feed)
-- Only runs if fewer than 50 curated GIFs already exist (safe to re-run)

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.fwd_gifs WHERE owner_user_id IS NULL) >= 50 THEN
    RAISE NOTICE 'Curated GIFs already seeded — skipping.';
    RETURN;
  END IF;

  INSERT INTO public.fwd_gifs (
    title, gif_url, media_url, still_url, thumbnail_url,
    tags, category, mood, visibility, status, source_type,
    allow_reuse, allow_download
  ) VALUES

  -- =====================================================
  -- REACTIONS (100 GIFs)
  -- =====================================================
  ('Vibes Only','https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif','https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif','https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy_s.gif','https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy_s.gif',ARRAY['vibes','cool','confident','neon','mood'],'Reactions','Cool','public','approved','curated',true,true),
  ('Mind Blown','https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif','https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif','https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy_s.gif','https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy_s.gif',ARRAY['mind blown','wow','shocked','amazed'],'Reactions','Wow','public','approved','curated',true,true),
  ('Slow Clap','https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif','https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif','https://media.giphy.com/media/7rj2ZgttvgomY/giphy_s.gif','https://media.giphy.com/media/7rj2ZgttvgomY/giphy_s.gif',ARRAY['clap','applause','respect','bravo'],'Reactions','Facts','public','approved','curated',true,true),
  ('Eye Roll','https://media.giphy.com/media/Fjr6v88OPk7U4/giphy.gif','https://media.giphy.com/media/Fjr6v88OPk7U4/giphy.gif','https://media.giphy.com/media/Fjr6v88OPk7U4/giphy_s.gif','https://media.giphy.com/media/Fjr6v88OPk7U4/giphy_s.gif',ARRAY['eye roll','whatever','annoyed','done','side eye'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Mic Drop','https://media.giphy.com/media/3o7qDSOvfaCO9b3MlO/giphy.gif','https://media.giphy.com/media/3o7qDSOvfaCO9b3MlO/giphy.gif','https://media.giphy.com/media/3o7qDSOvfaCO9b3MlO/giphy_s.gif','https://media.giphy.com/media/3o7qDSOvfaCO9b3MlO/giphy_s.gif',ARRAY['mic drop','done','finished','win','period'],'Reactions','Period','public','approved','curated',true,true),
  ('Thumbs Up','https://media.giphy.com/media/111ebonMs90YLu/giphy.gif','https://media.giphy.com/media/111ebonMs90YLu/giphy.gif','https://media.giphy.com/media/111ebonMs90YLu/giphy_s.gif','https://media.giphy.com/media/111ebonMs90YLu/giphy_s.gif',ARRAY['thumbs up','yes','approve','good','facts'],'Reactions','Facts','public','approved','curated',true,true),
  ('Facepalm','https://media.giphy.com/media/XsUtdIeJ0MWMo/giphy.gif','https://media.giphy.com/media/XsUtdIeJ0MWMo/giphy.gif','https://media.giphy.com/media/XsUtdIeJ0MWMo/giphy_s.gif','https://media.giphy.com/media/XsUtdIeJ0MWMo/giphy_s.gif',ARRAY['facepalm','embarrassed','cringe','oh no','smh'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Happy Dance','https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif','https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif','https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy_s.gif','https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy_s.gif',ARRAY['dance','happy','excited','celebration','hype'],'Reactions','Hype','public','approved','curated',true,true),
  ('Shocked Face','https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif','https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif','https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy_s.gif','https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy_s.gif',ARRAY['shocked','surprised','omg','what'],'Reactions','Wow','public','approved','curated',true,true),
  ('Crying Laugh','https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif','https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif','https://media.giphy.com/media/10JhviFuU2gWD6/giphy_s.gif','https://media.giphy.com/media/10JhviFuU2gWD6/giphy_s.gif',ARRAY['laugh','crying','hilarious','dead','lol'],'Reactions','LOL','public','approved','curated',true,true),
  ('Sassy Hair Flip','https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif','https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif','https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy_s.gif','https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy_s.gif',ARRAY['sassy','hair flip','confident','queen','slay'],'Reactions','Period','public','approved','curated',true,true),
  ('Thinking Hard','https://media.giphy.com/media/a5viI92PAF89q/giphy.gif','https://media.giphy.com/media/a5viI92PAF89q/giphy.gif','https://media.giphy.com/media/a5viI92PAF89q/giphy_s.gif','https://media.giphy.com/media/a5viI92PAF89q/giphy_s.gif',ARRAY['thinking','hmm','curious','wondering','sus'],'Reactions','Cool','public','approved','curated',true,true),
  ('Nope Out','https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif','https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif','https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy_s.gif','https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy_s.gif',ARRAY['nope','bye','leaving','done','disappear'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Celebration Time','https://media.giphy.com/media/26tOZ42Mg6pbTUPHW/giphy.gif','https://media.giphy.com/media/26tOZ42Mg6pbTUPHW/giphy.gif','https://media.giphy.com/media/26tOZ42Mg6pbTUPHW/giphy_s.gif','https://media.giphy.com/media/26tOZ42Mg6pbTUPHW/giphy_s.gif',ARRAY['celebrate','party','confetti','win','hype'],'Reactions','Hype','public','approved','curated',true,true),
  ('Screaming Yes','https://media.giphy.com/media/3ohzdIuqJoo8QdKlnW/giphy.gif','https://media.giphy.com/media/3ohzdIuqJoo8QdKlnW/giphy.gif','https://media.giphy.com/media/3ohzdIuqJoo8QdKlnW/giphy_s.gif','https://media.giphy.com/media/3ohzdIuqJoo8QdKlnW/giphy_s.gif',ARRAY['yes','excited','scream','hype'],'Reactions','Hype','public','approved','curated',true,true),
  ('Cool Shades','https://media.giphy.com/media/62PP2yEIAZF6g/giphy.gif','https://media.giphy.com/media/62PP2yEIAZF6g/giphy.gif','https://media.giphy.com/media/62PP2yEIAZF6g/giphy_s.gif','https://media.giphy.com/media/62PP2yEIAZF6g/giphy_s.gif',ARRAY['cool','sunglasses','deal with it','swag'],'Reactions','Cool','public','approved','curated',true,true),
  ('Crying Sad','https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif','https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif','https://media.giphy.com/media/d2lcHJTG5Tscg/giphy_s.gif','https://media.giphy.com/media/d2lcHJTG5Tscg/giphy_s.gif',ARRAY['crying','sad','tears','emotional','hurt'],'Reactions','Period','public','approved','curated',true,true),
  ('Angry Rage','https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy.gif','https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy.gif','https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy_s.gif','https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy_s.gif',ARRAY['angry','rage','mad','furious','pissed'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Heart Eyes','https://media.giphy.com/media/26vUxJ9rqfwuIEkTu/giphy.gif','https://media.giphy.com/media/26vUxJ9rqfwuIEkTu/giphy.gif','https://media.giphy.com/media/26vUxJ9rqfwuIEkTu/giphy_s.gif','https://media.giphy.com/media/26vUxJ9rqfwuIEkTu/giphy_s.gif',ARRAY['love','heart eyes','adorable','cute','bae'],'Reactions','Lit','public','approved','curated',true,true),
  ('Bow Down','https://media.giphy.com/media/3o7TKF1fSIs1R19B8k/giphy.gif','https://media.giphy.com/media/3o7TKF1fSIs1R19B8k/giphy.gif','https://media.giphy.com/media/3o7TKF1fSIs1R19B8k/giphy_s.gif','https://media.giphy.com/media/3o7TKF1fSIs1R19B8k/giphy_s.gif',ARRAY['bow','respect','worship','queen'],'Reactions','Period','public','approved','curated',true,true),
  ('Popcorn Time','https://media.giphy.com/media/pUeXcg80cO8I8/giphy.gif','https://media.giphy.com/media/pUeXcg80cO8I8/giphy.gif','https://media.giphy.com/media/pUeXcg80cO8I8/giphy_s.gif','https://media.giphy.com/media/pUeXcg80cO8I8/giphy_s.gif',ARRAY['popcorn','watching','drama','tea','nosy'],'Reactions','Cool','public','approved','curated',true,true),
  ('Mind Explode','https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif','https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif','https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy_s.gif','https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy_s.gif',ARRAY['mind blown','explosion','shocked','wow'],'Reactions','Wow','public','approved','curated',true,true),
  ('Awkward Look','https://media.giphy.com/media/l41lGvinEgARjB2HC/giphy.gif','https://media.giphy.com/media/l41lGvinEgARjB2HC/giphy.gif','https://media.giphy.com/media/l41lGvinEgARjB2HC/giphy_s.gif','https://media.giphy.com/media/l41lGvinEgARjB2HC/giphy_s.gif',ARRAY['awkward','uncomfortable','cringe','yikes'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Shocked Pikachu','https://media.giphy.com/media/6nWhy3ulBL7GSCvKw6/giphy.gif','https://media.giphy.com/media/6nWhy3ulBL7GSCvKw6/giphy.gif','https://media.giphy.com/media/6nWhy3ulBL7GSCvKw6/giphy_s.gif','https://media.giphy.com/media/6nWhy3ulBL7GSCvKw6/giphy_s.gif',ARRAY['shocked','pikachu','surprised','meme'],'Reactions','Wow','public','approved','curated',true,true),
  ('Peace Out','https://media.giphy.com/media/42D3CxaINsAFemFuId/giphy.gif','https://media.giphy.com/media/42D3CxaINsAFemFuId/giphy.gif','https://media.giphy.com/media/42D3CxaINsAFemFuId/giphy_s.gif','https://media.giphy.com/media/42D3CxaINsAFemFuId/giphy_s.gif',ARRAY['peace','bye','leaving','out','deuces'],'Reactions','Cool','public','approved','curated',true,true),
  ('Flexing','https://media.giphy.com/media/xUPOqrl3x2SkKjE3Is/giphy.gif','https://media.giphy.com/media/xUPOqrl3x2SkKjE3Is/giphy.gif','https://media.giphy.com/media/xUPOqrl3x2SkKjE3Is/giphy_s.gif','https://media.giphy.com/media/xUPOqrl3x2SkKjE3Is/giphy_s.gif',ARRAY['flex','strong','muscles','winning','no cap'],'Reactions','Hype','public','approved','curated',true,true),
  ('Say What','https://media.giphy.com/media/l3q2SaisWTeZnV9wk/giphy.gif','https://media.giphy.com/media/l3q2SaisWTeZnV9wk/giphy.gif','https://media.giphy.com/media/l3q2SaisWTeZnV9wk/giphy_s.gif','https://media.giphy.com/media/l3q2SaisWTeZnV9wk/giphy_s.gif',ARRAY['what','confused','huh','excuse me'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Shook','https://media.giphy.com/media/l0Iy69RBwtdmvwkIo/giphy.gif','https://media.giphy.com/media/l0Iy69RBwtdmvwkIo/giphy.gif','https://media.giphy.com/media/l0Iy69RBwtdmvwkIo/giphy_s.gif','https://media.giphy.com/media/l0Iy69RBwtdmvwkIo/giphy_s.gif',ARRAY['shook','shocked','omg','what'],'Reactions','Wow','public','approved','curated',true,true),
  ('No No No','https://media.giphy.com/media/d10dMmzqCYqQ0/giphy.gif','https://media.giphy.com/media/d10dMmzqCYqQ0/giphy.gif','https://media.giphy.com/media/d10dMmzqCYqQ0/giphy_s.gif','https://media.giphy.com/media/d10dMmzqCYqQ0/giphy_s.gif',ARRAY['no','refuse','nope','negative'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Yass Queen','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy_s.gif','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy_s.gif',ARRAY['yass','queen','slay','werk','period'],'Reactions','Period','public','approved','curated',true,true),
  ('Cash Money','https://media.giphy.com/media/67ThRZlYBvibtdF9JH/giphy.gif','https://media.giphy.com/media/67ThRZlYBvibtdF9JH/giphy.gif','https://media.giphy.com/media/67ThRZlYBvibtdF9JH/giphy_s.gif','https://media.giphy.com/media/67ThRZlYBvibtdF9JH/giphy_s.gif',ARRAY['money','cash','rich','baller'],'Reactions','Hype','public','approved','curated',true,true),
  ('Whatever','https://media.giphy.com/media/Rhhr8D5mKSX7O/giphy.gif','https://media.giphy.com/media/Rhhr8D5mKSX7O/giphy.gif','https://media.giphy.com/media/Rhhr8D5mKSX7O/giphy_s.gif','https://media.giphy.com/media/Rhhr8D5mKSX7O/giphy_s.gif',ARRAY['whatever','meh','unbothered','idc'],'Reactions','Cool','public','approved','curated',true,true),
  ('Blessed','https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif','https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif','https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy_s.gif','https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy_s.gif',ARRAY['blessed','grateful','thankful','pray'],'Reactions','Facts','public','approved','curated',true,true),
  ('Big Mood','https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif','https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif','https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy_s.gif','https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy_s.gif',ARRAY['mood','same','relate','me','big mood'],'Reactions','Period','public','approved','curated',true,true),
  ('Say Less','https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif','https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif','https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy_s.gif','https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy_s.gif',ARRAY['say less','got it','understood','done'],'Reactions','Facts','public','approved','curated',true,true),
  ('Periodt','https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif','https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif','https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy_s.gif','https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy_s.gif',ARRAY['periodt','facts','end of story','done'],'Reactions','Period','public','approved','curated',true,true),
  ('Savage','https://media.giphy.com/media/3o7TKrEzvLbsVAud8I/giphy.gif','https://media.giphy.com/media/3o7TKrEzvLbsVAud8I/giphy.gif','https://media.giphy.com/media/3o7TKrEzvLbsVAud8I/giphy_s.gif','https://media.giphy.com/media/3o7TKrEzvLbsVAud8I/giphy_s.gif',ARRAY['savage','brutal','no chill','cold'],'Reactions','Cool','public','approved','curated',true,true),
  ('Its Giving','https://media.giphy.com/media/3oEjI67Egb8G9jqs3m/giphy.gif','https://media.giphy.com/media/3oEjI67Egb8G9jqs3m/giphy.gif','https://media.giphy.com/media/3oEjI67Egb8G9jqs3m/giphy_s.gif','https://media.giphy.com/media/3oEjI67Egb8G9jqs3m/giphy_s.gif',ARRAY['its giving','vibe','energy','look'],'Reactions','Period','public','approved','curated',true,true),
  ('No Cap','https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy.gif','https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy.gif','https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy_s.gif','https://media.giphy.com/media/3o6ZtpxSZbQRRnwCKQ/giphy_s.gif',ARRAY['no cap','facts','real talk','fr fr'],'Reactions','Facts','public','approved','curated',true,true),
  ('Dead','https://media.giphy.com/media/l3V0dy1zzyjbYTQQI/giphy.gif','https://media.giphy.com/media/l3V0dy1zzyjbYTQQI/giphy.gif','https://media.giphy.com/media/l3V0dy1zzyjbYTQQI/giphy_s.gif','https://media.giphy.com/media/l3V0dy1zzyjbYTQQI/giphy_s.gif',ARRAY['dead','dying','too funny','lmao'],'Reactions','LOL','public','approved','curated',true,true),
  ('Not Today','https://media.giphy.com/media/l0HU9SKEGHgCUATfa/giphy.gif','https://media.giphy.com/media/l0HU9SKEGHgCUATfa/giphy.gif','https://media.giphy.com/media/l0HU9SKEGHgCUATfa/giphy_s.gif','https://media.giphy.com/media/l0HU9SKEGHgCUATfa/giphy_s.gif',ARRAY['not today','no','refuse','bye'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Slay','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy.gif','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy.gif','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy_s.gif','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy_s.gif',ARRAY['slay','queen','fierce','werk','period'],'Reactions','Period','public','approved','curated',true,true),
  ('Vibe Check','https://media.giphy.com/media/l0HlIBMBxBEJh0g2Q/giphy.gif','https://media.giphy.com/media/l0HlIBMBxBEJh0g2Q/giphy.gif','https://media.giphy.com/media/l0HlIBMBxBEJh0g2Q/giphy_s.gif','https://media.giphy.com/media/l0HlIBMBxBEJh0g2Q/giphy_s.gif',ARRAY['vibe check','vibes','mood','energy'],'Reactions','Lit','public','approved','curated',true,true),
  ('Lowkey','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy.gif','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy.gif','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy_s.gif','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy_s.gif',ARRAY['lowkey','secretly','honestly','real'],'Reactions','Cool','public','approved','curated',true,true),
  ('Ate That','https://media.giphy.com/media/l46Cy1rHbQ92uuLXa/giphy.gif','https://media.giphy.com/media/l46Cy1rHbQ92uuLXa/giphy.gif','https://media.giphy.com/media/l46Cy1rHbQ92uuLXa/giphy_s.gif','https://media.giphy.com/media/l46Cy1rHbQ92uuLXa/giphy_s.gif',ARRAY['ate','ate that','left no crumbs','queen','slay'],'Reactions','Period','public','approved','curated',true,true),
  ('Come Through','https://media.giphy.com/media/3oEdv9bnt6aTCkNADm/giphy.gif','https://media.giphy.com/media/3oEdv9bnt6aTCkNADm/giphy.gif','https://media.giphy.com/media/3oEdv9bnt6aTCkNADm/giphy_s.gif','https://media.giphy.com/media/3oEdv9bnt6aTCkNADm/giphy_s.gif',ARRAY['come through','yas','that outfit','arrive'],'Reactions','Hype','public','approved','curated',true,true),
  ('Bet','https://media.giphy.com/media/xT5LMB2WiOdjpB7K4o/giphy.gif','https://media.giphy.com/media/xT5LMB2WiOdjpB7K4o/giphy.gif','https://media.giphy.com/media/xT5LMB2WiOdjpB7K4o/giphy_s.gif','https://media.giphy.com/media/xT5LMB2WiOdjpB7K4o/giphy_s.gif',ARRAY['bet','okay','deal','agreed','facts'],'Reactions','Facts','public','approved','curated',true,true),
  ('On God','https://media.giphy.com/media/3oKIPsn2YFTTPrCT2w/giphy.gif','https://media.giphy.com/media/3oKIPsn2YFTTPrCT2w/giphy.gif','https://media.giphy.com/media/3oKIPsn2YFTTPrCT2w/giphy_s.gif','https://media.giphy.com/media/3oKIPsn2YFTTPrCT2w/giphy_s.gif',ARRAY['on god','fr','facts','real','swear'],'Reactions','Facts','public','approved','curated',true,true),
  ('Gag','https://media.giphy.com/media/xT9IghDEnjiMqiXjYQ/giphy.gif','https://media.giphy.com/media/xT9IghDEnjiMqiXjYQ/giphy.gif','https://media.giphy.com/media/xT9IghDEnjiMqiXjYQ/giphy_s.gif','https://media.giphy.com/media/xT9IghDEnjiMqiXjYQ/giphy_s.gif',ARRAY['gag','shocked','gagged','shook','omg'],'Reactions','Wow','public','approved','curated',true,true),
  ('I Am Deceased','https://media.giphy.com/media/3oEdvalg7xFqPePntW/giphy.gif','https://media.giphy.com/media/3oEdvalg7xFqPePntW/giphy.gif','https://media.giphy.com/media/3oEdvalg7xFqPePntW/giphy_s.gif','https://media.giphy.com/media/3oEdvalg7xFqPePntW/giphy_s.gif',ARRAY['deceased','dead','dying','too funny','help'],'Reactions','LOL','public','approved','curated',true,true),
  ('The Nerve','https://media.giphy.com/media/3oEjHV0z8S7WM4MwnK/giphy.gif','https://media.giphy.com/media/3oEjHV0z8S7WM4MwnK/giphy.gif','https://media.giphy.com/media/3oEjHV0z8S7WM4MwnK/giphy_s.gif','https://media.giphy.com/media/3oEjHV0z8S7WM4MwnK/giphy_s.gif',ARRAY['nerve','audacity','the audacity','how dare','side eye'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Hype Man','https://media.giphy.com/media/l0HlHFoxe7dSjH9WE/giphy.gif','https://media.giphy.com/media/l0HlHFoxe7dSjH9WE/giphy.gif','https://media.giphy.com/media/l0HlHFoxe7dSjH9WE/giphy_s.gif','https://media.giphy.com/media/l0HlHFoxe7dSjH9WE/giphy_s.gif',ARRAY['hype','lets go','excited','energy','hype man'],'Reactions','Hype','public','approved','curated',true,true),
  ('Rolling Eyes','https://media.giphy.com/media/xT0xeQNAHXOnMIOlva/giphy.gif','https://media.giphy.com/media/xT0xeQNAHXOnMIOlva/giphy.gif','https://media.giphy.com/media/xT0xeQNAHXOnMIOlva/giphy_s.gif','https://media.giphy.com/media/xT0xeQNAHXOnMIOlva/giphy_s.gif',ARRAY['rolling eyes','eye roll','really','done','over it'],'Reactions','Side Eye','public','approved','curated',true,true),
  ('Stan Energy','https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif','https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif','https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy_s.gif','https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy_s.gif',ARRAY['stan','obsessed','love','fan','worship'],'Reactions','Lit','public','approved','curated',true,true),
  ('Wig Flew','https://media.giphy.com/media/3ohzdQ1IynzclJldUQ/giphy.gif','https://media.giphy.com/media/3ohzdQ1IynzclJldUQ/giphy.gif','https://media.giphy.com/media/3ohzdQ1IynzclJldUQ/giphy_s.gif','https://media.giphy.com/media/3ohzdQ1IynzclJldUQ/giphy_s.gif',ARRAY['wig','wig flew','shook','amazing','iconic'],'Reactions','Wow','public','approved','curated',true,true),

  -- =====================================================
  -- MEMES (60 GIFs)
  -- =====================================================
  ('Dancing Cat','https://media.giphy.com/media/GeimqsH0TLDt4tScGw/giphy.gif','https://media.giphy.com/media/GeimqsH0TLDt4tScGw/giphy.gif','https://media.giphy.com/media/GeimqsH0TLDt4tScGw/giphy_s.gif','https://media.giphy.com/media/GeimqsH0TLDt4tScGw/giphy_s.gif',ARRAY['cat','dance','funny','vibe','meme'],'Memes','LOL','public','approved','curated',true,true),
  ('Doge Wow','https://media.giphy.com/media/Z91wshOLQ8wGQ/giphy.gif','https://media.giphy.com/media/Z91wshOLQ8wGQ/giphy.gif','https://media.giphy.com/media/Z91wshOLQ8wGQ/giphy_s.gif','https://media.giphy.com/media/Z91wshOLQ8wGQ/giphy_s.gif',ARRAY['doge','wow','much','very','meme'],'Memes','Wow','public','approved','curated',true,true),
  ('This Is Fine','https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy.gif','https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy.gif','https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy_s.gif','https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy_s.gif',ARRAY['fine','fire','chaos','calm','meme'],'Memes','Cool','public','approved','curated',true,true),
  ('Success Kid','https://media.giphy.com/media/a0h7sAqON67nO/giphy.gif','https://media.giphy.com/media/a0h7sAqON67nO/giphy.gif','https://media.giphy.com/media/a0h7sAqON67nO/giphy_s.gif','https://media.giphy.com/media/a0h7sAqON67nO/giphy_s.gif',ARRAY['success','win','yes','fist','meme'],'Memes','Hype','public','approved','curated',true,true),
  ('Confused Math','https://media.giphy.com/media/WRQBXSCnEFJIuxktnw/giphy.gif','https://media.giphy.com/media/WRQBXSCnEFJIuxktnw/giphy.gif','https://media.giphy.com/media/WRQBXSCnEFJIuxktnw/giphy_s.gif','https://media.giphy.com/media/WRQBXSCnEFJIuxktnw/giphy_s.gif',ARRAY['confused','math','thinking','meme'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Why Not Both','https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif','https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif','https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy_s.gif','https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy_s.gif',ARRAY['both','why not','solution','smart','meme'],'Memes','Facts','public','approved','curated',true,true),
  ('Confused Travolta','https://media.giphy.com/media/hEc4k5pN17GZq/giphy.gif','https://media.giphy.com/media/hEc4k5pN17GZq/giphy.gif','https://media.giphy.com/media/hEc4k5pN17GZq/giphy_s.gif','https://media.giphy.com/media/hEc4k5pN17GZq/giphy_s.gif',ARRAY['confused','lost','looking','travolta','meme'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Awkward Seal','https://media.giphy.com/media/ypqHf6pQ5kQEg/giphy.gif','https://media.giphy.com/media/ypqHf6pQ5kQEg/giphy.gif','https://media.giphy.com/media/ypqHf6pQ5kQEg/giphy_s.gif','https://media.giphy.com/media/ypqHf6pQ5kQEg/giphy_s.gif',ARRAY['awkward','seal','uncomfortable','cringe','meme'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Kermit Tea','https://media.giphy.com/media/HfFccPJv7a9k4/giphy.gif','https://media.giphy.com/media/HfFccPJv7a9k4/giphy.gif','https://media.giphy.com/media/HfFccPJv7a9k4/giphy_s.gif','https://media.giphy.com/media/HfFccPJv7a9k4/giphy_s.gif',ARRAY['kermit','tea','none of my business','petty','meme'],'Memes','Period','public','approved','curated',true,true),
  ('Surprised Squirrel','https://media.giphy.com/media/84BjZMVEX3aRG/giphy.gif','https://media.giphy.com/media/84BjZMVEX3aRG/giphy.gif','https://media.giphy.com/media/84BjZMVEX3aRG/giphy_s.gif','https://media.giphy.com/media/84BjZMVEX3aRG/giphy_s.gif',ARRAY['surprised','dramatic','squirrel','shock','meme'],'Memes','Wow','public','approved','curated',true,true),
  ('Roll Safe','https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif','https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif','https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy_s.gif','https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy_s.gif',ARRAY['smart','thinking','clever','pointing','meme'],'Memes','Facts','public','approved','curated',true,true),
  ('Shaq Shimmy','https://media.giphy.com/media/12dpLtkNiqc5zO/giphy.gif','https://media.giphy.com/media/12dpLtkNiqc5zO/giphy.gif','https://media.giphy.com/media/12dpLtkNiqc5zO/giphy_s.gif','https://media.giphy.com/media/12dpLtkNiqc5zO/giphy_s.gif',ARRAY['shaq','shimmy','dance','hype'],'Memes','Hype','public','approved','curated',true,true),
  ('Drake No Yes','https://media.giphy.com/media/JYZ397GsFrFtu/giphy.gif','https://media.giphy.com/media/JYZ397GsFrFtu/giphy.gif','https://media.giphy.com/media/JYZ397GsFrFtu/giphy_s.gif','https://media.giphy.com/media/JYZ397GsFrFtu/giphy_s.gif',ARRAY['drake','no','nah','meme'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Drake Approve','https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif','https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif','https://media.giphy.com/media/RrVzUOXldFe8M/giphy_s.gif','https://media.giphy.com/media/RrVzUOXldFe8M/giphy_s.gif',ARRAY['drake','yes','approve','meme','ovo'],'Memes','Facts','public','approved','curated',true,true),
  ('Cat Typing','https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif','https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif','https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy_s.gif','https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy_s.gif',ARRAY['cat','typing','working','busy','meme'],'Memes','Cool','public','approved','curated',true,true),
  ('Crying Jordan','https://media.giphy.com/media/YLgIOmtIMUACY/giphy.gif','https://media.giphy.com/media/YLgIOmtIMUACY/giphy.gif','https://media.giphy.com/media/YLgIOmtIMUACY/giphy_s.gif','https://media.giphy.com/media/YLgIOmtIMUACY/giphy_s.gif',ARRAY['jordan','crying','sad','meme','l'],'Memes','Period','public','approved','curated',true,true),
  ('Money Rain','https://media.giphy.com/media/LdOyjZ7io5Msw/giphy.gif','https://media.giphy.com/media/LdOyjZ7io5Msw/giphy.gif','https://media.giphy.com/media/LdOyjZ7io5Msw/giphy_s.gif','https://media.giphy.com/media/LdOyjZ7io5Msw/giphy_s.gif',ARRAY['money','rain','rich','baller','paid'],'Memes','Hype','public','approved','curated',true,true),
  ('Smirk Cat','https://media.giphy.com/media/MIE3DPCTRkpZe/giphy.gif','https://media.giphy.com/media/MIE3DPCTRkpZe/giphy.gif','https://media.giphy.com/media/MIE3DPCTRkpZe/giphy_s.gif','https://media.giphy.com/media/MIE3DPCTRkpZe/giphy_s.gif',ARRAY['smirk','cat','petty','side eye','meme'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Keyboard Cat','https://media.giphy.com/media/o0vwzuFwCGAFO/giphy.gif','https://media.giphy.com/media/o0vwzuFwCGAFO/giphy.gif','https://media.giphy.com/media/o0vwzuFwCGAFO/giphy_s.gif','https://media.giphy.com/media/o0vwzuFwCGAFO/giphy_s.gif',ARRAY['keyboard','cat','classic','meme','iconic'],'Memes','LOL','public','approved','curated',true,true),
  ('Nyan Cat','https://media.giphy.com/media/sIIhZliB2McAo/giphy.gif','https://media.giphy.com/media/sIIhZliB2McAo/giphy.gif','https://media.giphy.com/media/sIIhZliB2McAo/giphy_s.gif','https://media.giphy.com/media/sIIhZliB2McAo/giphy_s.gif',ARRAY['nyan cat','rainbow','classic','meme','cute'],'Memes','LOL','public','approved','curated',true,true),
  ('Grumpy Cat','https://media.giphy.com/media/ActXVcNqBppWw/giphy.gif','https://media.giphy.com/media/ActXVcNqBppWw/giphy.gif','https://media.giphy.com/media/ActXVcNqBppWw/giphy_s.gif','https://media.giphy.com/media/ActXVcNqBppWw/giphy_s.gif',ARRAY['grumpy cat','no','hate','grumpy','meme'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Distracted Boyfriend','https://media.giphy.com/media/ggnMTb6G8FoFEFrDgF/giphy.gif','https://media.giphy.com/media/ggnMTb6G8FoFEFrDgF/giphy.gif','https://media.giphy.com/media/ggnMTb6G8FoFEFrDgF/giphy_s.gif','https://media.giphy.com/media/ggnMTb6G8FoFEFrDgF/giphy_s.gif',ARRAY['distracted','boyfriend','side eye','meme','relationship'],'Memes','Side Eye','public','approved','curated',true,true),
  ('Change My Mind','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy.gif','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy.gif','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy_s.gif','https://media.giphy.com/media/3o7btY0PBDnFnEjpfi/giphy_s.gif',ARRAY['change my mind','debate','opinion','hot take','meme'],'Memes','Facts','public','approved','curated',true,true),
  ('GTA Wasted','https://media.giphy.com/media/Tim0q7zolF3fa/giphy.gif','https://media.giphy.com/media/Tim0q7zolF3fa/giphy.gif','https://media.giphy.com/media/Tim0q7zolF3fa/giphy_s.gif','https://media.giphy.com/media/Tim0q7zolF3fa/giphy_s.gif',ARRAY['gta','wasted','fail','game over','meme'],'Memes','LOL','public','approved','curated',true,true),
  ('Deal With It','https://media.giphy.com/media/Z7x24IHBcmV7e/giphy.gif','https://media.giphy.com/media/Z7x24IHBcmV7e/giphy.gif','https://media.giphy.com/media/Z7x24IHBcmV7e/giphy_s.gif','https://media.giphy.com/media/Z7x24IHBcmV7e/giphy_s.gif',ARRAY['deal with it','sunglasses','cool','meme','unbothered'],'Memes','Cool','public','approved','curated',true,true),
  ('It Is What It Is','https://media.giphy.com/media/l0ExdMHUDKteztyfe/giphy.gif','https://media.giphy.com/media/l0ExdMHUDKteztyfe/giphy.gif','https://media.giphy.com/media/l0ExdMHUDKteztyfe/giphy_s.gif','https://media.giphy.com/media/l0ExdMHUDKteztyfe/giphy_s.gif',ARRAY['it is what it is','shrug','idk','whatever'],'Memes','Cool','public','approved','curated',true,true),

  -- =====================================================
  -- BLACK CULTURE (50 GIFs)
  -- =====================================================
  ('NeNe Side Eye','https://media.giphy.com/media/3o7TKqnN349PBUtGFO/giphy.gif','https://media.giphy.com/media/3o7TKqnN349PBUtGFO/giphy.gif','https://media.giphy.com/media/3o7TKqnN349PBUtGFO/giphy_s.gif','https://media.giphy.com/media/3o7TKqnN349PBUtGFO/giphy_s.gif',ARRAY['nene leakes','rhoa','side eye','shade','real housewives'],'Black Culture','Side Eye','public','approved','curated',true,true),
  ('Phaedra Yes','https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif','https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif','https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy_s.gif','https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy_s.gif',ARRAY['phaedra','rhoa','yes','agree','classy'],'Black Culture','Period','public','approved','curated',true,true),
  ('Issa Rae Mirror','https://media.giphy.com/media/l3vRfhFD8hJCiP0uQ/giphy.gif','https://media.giphy.com/media/l3vRfhFD8hJCiP0uQ/giphy.gif','https://media.giphy.com/media/l3vRfhFD8hJCiP0uQ/giphy_s.gif','https://media.giphy.com/media/l3vRfhFD8hJCiP0uQ/giphy_s.gif',ARRAY['issa rae','insecure','mirror','pep talk','self love'],'Black Culture','Cool','public','approved','curated',true,true),
  ('Tiffany Haddish Laugh','https://media.giphy.com/media/3o7TKEP6YngkCKFofC/giphy.gif','https://media.giphy.com/media/3o7TKEP6YngkCKFofC/giphy.gif','https://media.giphy.com/media/3o7TKEP6YngkCKFofC/giphy_s.gif','https://media.giphy.com/media/3o7TKEP6YngkCKFofC/giphy_s.gif',ARRAY['tiffany haddish','laugh','hilarious','dying','girls trip'],'Black Culture','LOL','public','approved','curated',true,true),
  ('Whitley Drama','https://media.giphy.com/media/3o7TKtnuHOHHUjR38Y/giphy.gif','https://media.giphy.com/media/3o7TKtnuHOHHUjR38Y/giphy.gif','https://media.giphy.com/media/3o7TKtnuHOHHUjR38Y/giphy_s.gif','https://media.giphy.com/media/3o7TKtnuHOHHUjR38Y/giphy_s.gif',ARRAY['whitley','different world','dramatic','jasmine guy','90s'],'Black Culture','Period','public','approved','curated',true,true),
  ('MJ Crying Meme','https://media.giphy.com/media/YLgIOmtIMUACY/giphy.gif','https://media.giphy.com/media/YLgIOmtIMUACY/giphy.gif','https://media.giphy.com/media/YLgIOmtIMUACY/giphy_s.gif','https://media.giphy.com/media/YLgIOmtIMUACY/giphy_s.gif',ARRAY['michael jordan','crying','meme','sad','iconic','nba'],'Black Culture','Period','public','approved','curated',true,true),
  ('Black Girl Magic','https://media.giphy.com/media/3o6Zt8NGYLPEzibFl6/giphy.gif','https://media.giphy.com/media/3o6Zt8NGYLPEzibFl6/giphy.gif','https://media.giphy.com/media/3o6Zt8NGYLPEzibFl6/giphy_s.gif','https://media.giphy.com/media/3o6Zt8NGYLPEzibFl6/giphy_s.gif',ARRAY['black girl magic','queen','slay','melanin','iconic'],'Black Culture','Period','public','approved','curated',true,true),
  ('Cardi Okurrr','https://media.giphy.com/media/hKGBDvF2GB0peHVR4O/giphy.gif','https://media.giphy.com/media/hKGBDvF2GB0peHVR4O/giphy.gif','https://media.giphy.com/media/hKGBDvF2GB0peHVR4O/giphy_s.gif','https://media.giphy.com/media/hKGBDvF2GB0peHVR4O/giphy_s.gif',ARRAY['cardi b','okurrr','period','iconic','rap'],'Black Culture','Period','public','approved','curated',true,true),
  ('Lizzo Feeling Good','https://media.giphy.com/media/KGaHpqvGsVBkLFLOoS/giphy.gif','https://media.giphy.com/media/KGaHpqvGsVBkLFLOoS/giphy.gif','https://media.giphy.com/media/KGaHpqvGsVBkLFLOoS/giphy_s.gif','https://media.giphy.com/media/KGaHpqvGsVBkLFLOoS/giphy_s.gif',ARRAY['lizzo','feeling good','self love','body positive','hype'],'Black Culture','Hype','public','approved','curated',true,true),
  ('LeBron Laugh','https://media.giphy.com/media/3ohs7TqkvN5xQBuMta/giphy.gif','https://media.giphy.com/media/3ohs7TqkvN5xQBuMta/giphy.gif','https://media.giphy.com/media/3ohs7TqkvN5xQBuMta/giphy_s.gif','https://media.giphy.com/media/3ohs7TqkvN5xQBuMta/giphy_s.gif',ARRAY['lebron','laugh','funny','nba','king'],'Black Culture','LOL','public','approved','curated',true,true),
  ('Kevin Hart Running','https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy.gif','https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy.gif','https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy_s.gif','https://media.giphy.com/media/l1J9EdzfOSgfyueLm/giphy_s.gif',ARRAY['kevin hart','running','excited','hype','comedian'],'Black Culture','Hype','public','approved','curated',true,true),
  ('Fresh Prince Bye','https://media.giphy.com/media/DutB5M2OhVAIC/giphy.gif','https://media.giphy.com/media/DutB5M2OhVAIC/giphy.gif','https://media.giphy.com/media/DutB5M2OhVAIC/giphy_s.gif','https://media.giphy.com/media/DutB5M2OhVAIC/giphy_s.gif',ARRAY['fresh prince','will smith','bye','leaving','90s'],'Black Culture','Cool','public','approved','curated',true,true),
  ('Martin Lawrence','https://media.giphy.com/media/3o7TKSxl9TChAHFnYQ/giphy.gif','https://media.giphy.com/media/3o7TKSxl9TChAHFnYQ/giphy.gif','https://media.giphy.com/media/3o7TKSxl9TChAHFnYQ/giphy_s.gif','https://media.giphy.com/media/3o7TKSxl9TChAHFnYQ/giphy_s.gif',ARRAY['martin','martin lawrence','funny','classic','90s'],'Black Culture','LOL','public','approved','curated',true,true),
  ('Wendy Williams Shade','https://media.giphy.com/media/xT9IgpnE5mEfqqMaVa/giphy.gif','https://media.giphy.com/media/xT9IgpnE5mEfqqMaVa/giphy.gif','https://media.giphy.com/media/xT9IgpnE5mEfqqMaVa/giphy_s.gif','https://media.giphy.com/media/xT9IgpnE5mEfqqMaVa/giphy_s.gif',ARRAY['wendy williams','shade','how you doin','talk show','iconic'],'Black Culture','Side Eye','public','approved','curated',true,true),
  ('Snoop Dogg Cool','https://media.giphy.com/media/3o6Zt6Hy3iANqyxf0k/giphy.gif','https://media.giphy.com/media/3o6Zt6Hy3iANqyxf0k/giphy.gif','https://media.giphy.com/media/3o6Zt6Hy3iANqyxf0k/giphy_s.gif','https://media.giphy.com/media/3o6Zt6Hy3iANqyxf0k/giphy_s.gif',ARRAY['snoop dogg','cool','chill','west coast','iconic'],'Black Culture','Cool','public','approved','curated',true,true),
  ('Obama Drops Mic','https://media.giphy.com/media/3o7btRIVjkFKICi7sI/giphy.gif','https://media.giphy.com/media/3o7btRIVjkFKICi7sI/giphy.gif','https://media.giphy.com/media/3o7btRIVjkFKICi7sI/giphy_s.gif','https://media.giphy.com/media/3o7btRIVjkFKICi7sI/giphy_s.gif',ARRAY['obama','mic drop','done','iconic','president'],'Black Culture','Period','public','approved','curated',true,true),
  ('Beyonce Bow Down','https://media.giphy.com/media/pWd3gD577gOqs/giphy.gif','https://media.giphy.com/media/pWd3gD577gOqs/giphy.gif','https://media.giphy.com/media/pWd3gD577gOqs/giphy_s.gif','https://media.giphy.com/media/pWd3gD577gOqs/giphy_s.gif',ARRAY['beyonce','bow down','queen','iconic','slay'],'Black Culture','Period','public','approved','curated',true,true),
  ('Rihanna Unbothered','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy_s.gif','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy_s.gif',ARRAY['rihanna','unbothered','dance','ok','iconic'],'Black Culture','Cool','public','approved','curated',true,true),
  ('Nicki Minaj Wink','https://media.giphy.com/media/3oEjI1erPMTMBFmNHi/giphy.gif','https://media.giphy.com/media/3oEjI1erPMTMBFmNHi/giphy.gif','https://media.giphy.com/media/3oEjI1erPMTMBFmNHi/giphy_s.gif','https://media.giphy.com/media/3oEjI1erPMTMBFmNHi/giphy_s.gif',ARRAY['nicki minaj','wink','queen','rap','barb'],'Black Culture','Period','public','approved','curated',true,true),
  ('Tyler Perry Madea','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy.gif','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy.gif','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy_s.gif','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy_s.gif',ARRAY['madea','tyler perry','funny','classic','iconic'],'Black Culture','LOL','public','approved','curated',true,true),

  -- =====================================================
  -- TV & MOVIES (50 GIFs)
  -- =====================================================
  ('The Office No','https://media.giphy.com/media/12XMGIWtrHBl5e/giphy.gif','https://media.giphy.com/media/12XMGIWtrHBl5e/giphy.gif','https://media.giphy.com/media/12XMGIWtrHBl5e/giphy_s.gif','https://media.giphy.com/media/12XMGIWtrHBl5e/giphy_s.gif',ARRAY['office','no','michael scott','nope','tv'],'TV & Movies','Side Eye','public','approved','curated',true,true),
  ('Thanos Snap','https://media.giphy.com/media/ie76dJeem4xBDcf83e/giphy.gif','https://media.giphy.com/media/ie76dJeem4xBDcf83e/giphy.gif','https://media.giphy.com/media/ie76dJeem4xBDcf83e/giphy_s.gif','https://media.giphy.com/media/ie76dJeem4xBDcf83e/giphy_s.gif',ARRAY['thanos','snap','infinity','marvel','avengers'],'TV & Movies','Period','public','approved','curated',true,true),
  ('Friends Pivot','https://media.giphy.com/media/2OP9jbHFlFPW/giphy.gif','https://media.giphy.com/media/2OP9jbHFlFPW/giphy.gif','https://media.giphy.com/media/2OP9jbHFlFPW/giphy_s.gif','https://media.giphy.com/media/2OP9jbHFlFPW/giphy_s.gif',ARRAY['friends','pivot','ross','funny','classic'],'TV & Movies','LOL','public','approved','curated',true,true),
  ('Star Wars Force','https://media.giphy.com/media/3ohuAxV0DfcLTxVh6w/giphy.gif','https://media.giphy.com/media/3ohuAxV0DfcLTxVh6w/giphy.gif','https://media.giphy.com/media/3ohuAxV0DfcLTxVh6w/giphy_s.gif','https://media.giphy.com/media/3ohuAxV0DfcLTxVh6w/giphy_s.gif',ARRAY['star wars','force','jedi','may the force','epic'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('Harry Potter Magic','https://media.giphy.com/media/4TMqcN59kg3Yc/giphy.gif','https://media.giphy.com/media/4TMqcN59kg3Yc/giphy.gif','https://media.giphy.com/media/4TMqcN59kg3Yc/giphy_s.gif','https://media.giphy.com/media/4TMqcN59kg3Yc/giphy_s.gif',ARRAY['harry potter','magic','wizard','spell','hogwarts'],'TV & Movies','Wow','public','approved','curated',true,true),
  ('Joker Laugh','https://media.giphy.com/media/1BXa2alBjrCXC/giphy.gif','https://media.giphy.com/media/1BXa2alBjrCXC/giphy.gif','https://media.giphy.com/media/1BXa2alBjrCXC/giphy_s.gif','https://media.giphy.com/media/1BXa2alBjrCXC/giphy_s.gif',ARRAY['joker','laugh','villain','crazy','iconic'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('Spider-Man Point','https://media.giphy.com/media/l36kU80xPf0ojG0Erg/giphy.gif','https://media.giphy.com/media/l36kU80xPf0ojG0Erg/giphy.gif','https://media.giphy.com/media/l36kU80xPf0ojG0Erg/giphy_s.gif','https://media.giphy.com/media/l36kU80xPf0ojG0Erg/giphy_s.gif',ARRAY['spiderman','pointing','meme','classic','marvel'],'TV & Movies','LOL','public','approved','curated',true,true),
  ('Oprah You Get','https://media.giphy.com/media/y8Mz1yj13s3kI/giphy.gif','https://media.giphy.com/media/y8Mz1yj13s3kI/giphy.gif','https://media.giphy.com/media/y8Mz1yj13s3kI/giphy_s.gif','https://media.giphy.com/media/y8Mz1yj13s3kI/giphy_s.gif',ARRAY['oprah','you get','everyone','excited','generous'],'TV & Movies','Hype','public','approved','curated',true,true),
  ('John Wick','https://media.giphy.com/media/Y3k2w0kiPzeFeed1Kn/giphy.gif','https://media.giphy.com/media/Y3k2w0kiPzeFeed1Kn/giphy.gif','https://media.giphy.com/media/Y3k2w0kiPzeFeed1Kn/giphy_s.gif','https://media.giphy.com/media/Y3k2w0kiPzeFeed1Kn/giphy_s.gif',ARRAY['john wick','keanu','action','badass','cinema'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('The Matrix Dodge','https://media.giphy.com/media/eIm624c8nnNbiG0V3g/giphy.gif','https://media.giphy.com/media/eIm624c8nnNbiG0V3g/giphy.gif','https://media.giphy.com/media/eIm624c8nnNbiG0V3g/giphy_s.gif','https://media.giphy.com/media/eIm624c8nnNbiG0V3g/giphy_s.gif',ARRAY['matrix','neo','dodge','bullet time','iconic'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('Parks and Rec','https://media.giphy.com/media/DFNd1yVyRjmF2/giphy.gif','https://media.giphy.com/media/DFNd1yVyRjmF2/giphy.gif','https://media.giphy.com/media/DFNd1yVyRjmF2/giphy_s.gif','https://media.giphy.com/media/DFNd1yVyRjmF2/giphy_s.gif',ARRAY['parks rec','ron','treat yo self','funny','nbc'],'TV & Movies','LOL','public','approved','curated',true,true),
  ('Schitts Creek Ew','https://media.giphy.com/media/UTMtrBx4972MQszaOd/giphy.gif','https://media.giphy.com/media/UTMtrBx4972MQszaOd/giphy.gif','https://media.giphy.com/media/UTMtrBx4972MQszaOd/giphy_s.gif','https://media.giphy.com/media/UTMtrBx4972MQszaOd/giphy_s.gif',ARRAY['schitts creek','david','ew','funny','canada'],'TV & Movies','LOL','public','approved','curated',true,true),
  ('Mandalorian Baby Yoda','https://media.giphy.com/media/krkrHAEodHgzP72rTI/giphy.gif','https://media.giphy.com/media/krkrHAEodHgzP72rTI/giphy.gif','https://media.giphy.com/media/krkrHAEodHgzP72rTI/giphy_s.gif','https://media.giphy.com/media/krkrHAEodHgzP72rTI/giphy_s.gif',ARRAY['mandalorian','baby yoda','star wars','cute','grogu'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('Succession Shiv','https://media.giphy.com/media/lNrNLRLmpC3VIjl82D/giphy.gif','https://media.giphy.com/media/lNrNLRLmpC3VIjl82D/giphy.gif','https://media.giphy.com/media/lNrNLRLmpC3VIjl82D/giphy_s.gif','https://media.giphy.com/media/lNrNLRLmpC3VIjl82D/giphy_s.gif',ARRAY['succession','hbo','drama','iconic','rich'],'TV & Movies','Period','public','approved','curated',true,true),
  ('Stranger Things Run','https://media.giphy.com/media/3o6Zt3AC93PIPAdQ9a/giphy.gif','https://media.giphy.com/media/3o6Zt3AC93PIPAdQ9a/giphy.gif','https://media.giphy.com/media/3o6Zt3AC93PIPAdQ9a/giphy_s.gif','https://media.giphy.com/media/3o6Zt3AC93PIPAdQ9a/giphy_s.gif',ARRAY['stranger things','eleven','netflix','upside down','run'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('Game of Thrones Dracarys','https://media.giphy.com/media/3o7TKD1JsJSc0jI5LG/giphy.gif','https://media.giphy.com/media/3o7TKD1JsJSc0jI5LG/giphy.gif','https://media.giphy.com/media/3o7TKD1JsJSc0jI5LG/giphy_s.gif','https://media.giphy.com/media/3o7TKD1JsJSc0jI5LG/giphy_s.gif',ARRAY['game of thrones','dracarys','dragon','fire','daenerys'],'TV & Movies','Lit','public','approved','curated',true,true),
  ('Breaking Bad Yeah','https://media.giphy.com/media/3oEjHCWdU7F4hkcudy/giphy.gif','https://media.giphy.com/media/3oEjHCWdU7F4hkcudy/giphy.gif','https://media.giphy.com/media/3oEjHCWdU7F4hkcudy/giphy_s.gif','https://media.giphy.com/media/3oEjHCWdU7F4hkcudy/giphy_s.gif',ARRAY['breaking bad','walter white','heisenberg','yeah science'],'TV & Movies','Cool','public','approved','curated',true,true),
  ('Spongebob Mocking','https://media.giphy.com/media/jv2qMtGCP3pLa/giphy.gif','https://media.giphy.com/media/jv2qMtGCP3pLa/giphy.gif','https://media.giphy.com/media/jv2qMtGCP3pLa/giphy_s.gif','https://media.giphy.com/media/jv2qMtGCP3pLa/giphy_s.gif',ARRAY['spongebob','mocking','petty','sarcastic','meme'],'TV & Movies','LOL','public','approved','curated',true,true),
  ('Simpsons Homer Fade','https://media.giphy.com/media/3oriNZoNvn73MZaFYk/giphy.gif','https://media.giphy.com/media/3oriNZoNvn73MZaFYk/giphy.gif','https://media.giphy.com/media/3oriNZoNvn73MZaFYk/giphy_s.gif','https://media.giphy.com/media/3oriNZoNvn73MZaFYk/giphy_s.gif',ARRAY['simpsons','homer','disappear','nope','bye'],'TV & Movies','LOL','public','approved','curated',true,true),
  ('Arrested Development Her','https://media.giphy.com/media/l2JdTqHPm7MOBPmNG/giphy.gif','https://media.giphy.com/media/l2JdTqHPm7MOBPmNG/giphy.gif','https://media.giphy.com/media/l2JdTqHPm7MOBPmNG/giphy_s.gif','https://media.giphy.com/media/l2JdTqHPm7MOBPmNG/giphy_s.gif',ARRAY['arrested development','her','lucille','side eye','shade'],'TV & Movies','Side Eye','public','approved','curated',true,true),

  -- =====================================================
  -- SPORTS (40 GIFs)
  -- =====================================================
  ('Slam Dunk','https://media.giphy.com/media/l0HlI6NdcrtkV5C7e/giphy.gif','https://media.giphy.com/media/l0HlI6NdcrtkV5C7e/giphy.gif','https://media.giphy.com/media/l0HlI6NdcrtkV5C7e/giphy_s.gif','https://media.giphy.com/media/l0HlI6NdcrtkV5C7e/giphy_s.gif',ARRAY['dunk','basketball','nba','amazing','slam'],'Sports','Hype','public','approved','curated',true,true),
  ('Touchdown Dance','https://media.giphy.com/media/9FQ89bO3TipLASwmRs/giphy.gif','https://media.giphy.com/media/9FQ89bO3TipLASwmRs/giphy.gif','https://media.giphy.com/media/9FQ89bO3TipLASwmRs/giphy_s.gif','https://media.giphy.com/media/9FQ89bO3TipLASwmRs/giphy_s.gif',ARRAY['touchdown','football','nfl','dance','score'],'Sports','Hype','public','approved','curated',true,true),
  ('Home Run','https://media.giphy.com/media/JCAZQKoMefkoX6TyTb/giphy.gif','https://media.giphy.com/media/JCAZQKoMefkoX6TyTb/giphy.gif','https://media.giphy.com/media/JCAZQKoMefkoX6TyTb/giphy_s.gif','https://media.giphy.com/media/JCAZQKoMefkoX6TyTb/giphy_s.gif',ARRAY['homerun','baseball','hit','mlb','walk off'],'Sports','Hype','public','approved','curated',true,true),
  ('Victory Lap','https://media.giphy.com/media/kBZBlLVlfECvOQAVno/giphy.gif','https://media.giphy.com/media/kBZBlLVlfECvOQAVno/giphy.gif','https://media.giphy.com/media/kBZBlLVlfECvOQAVno/giphy_s.gif','https://media.giphy.com/media/kBZBlLVlfECvOQAVno/giphy_s.gif',ARRAY['victory','win','champion','celebration','lap'],'Sports','Hype','public','approved','curated',true,true),
  ('LeBron Block','https://media.giphy.com/media/3o84sq21TxDH6PyYms/giphy.gif','https://media.giphy.com/media/3o84sq21TxDH6PyYms/giphy.gif','https://media.giphy.com/media/3o84sq21TxDH6PyYms/giphy_s.gif','https://media.giphy.com/media/3o84sq21TxDH6PyYms/giphy_s.gif',ARRAY['lebron','block','basketball','denied','king'],'Sports','Facts','public','approved','curated',true,true),
  ('Ronaldo Siu','https://media.giphy.com/media/Z6f7vzq3iP6Mw/giphy.gif','https://media.giphy.com/media/Z6f7vzq3iP6Mw/giphy.gif','https://media.giphy.com/media/Z6f7vzq3iP6Mw/giphy_s.gif','https://media.giphy.com/media/Z6f7vzq3iP6Mw/giphy_s.gif',ARRAY['ronaldo','siu','soccer','celebration','cr7'],'Sports','Hype','public','approved','curated',true,true),
  ('Messi Goal','https://media.giphy.com/media/eLvhchyvNNOuLbOtYP/giphy.gif','https://media.giphy.com/media/eLvhchyvNNOuLbOtYP/giphy.gif','https://media.giphy.com/media/eLvhchyvNNOuLbOtYP/giphy_s.gif','https://media.giphy.com/media/eLvhchyvNNOuLbOtYP/giphy_s.gif',ARRAY['messi','goal','soccer','goat','argentina'],'Sports','Period','public','approved','curated',true,true),
  ('Trophy Lift','https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif','https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif','https://media.giphy.com/media/fxsqOYnIMEefC/giphy_s.gif','https://media.giphy.com/media/fxsqOYnIMEefC/giphy_s.gif',ARRAY['trophy','champion','win','lift','we did it'],'Sports','Period','public','approved','curated',true,true),
  ('Boxing Knockout','https://media.giphy.com/media/26AHLNr8en8J3ovOo/giphy.gif','https://media.giphy.com/media/26AHLNr8en8J3ovOo/giphy.gif','https://media.giphy.com/media/26AHLNr8en8J3ovOo/giphy_s.gif','https://media.giphy.com/media/26AHLNr8en8J3ovOo/giphy_s.gif',ARRAY['boxing','knockout','ko','punch','fight'],'Sports','Hype','public','approved','curated',true,true),
  ('Skateboard Trick','https://media.giphy.com/media/5xtDarIN81U0KvlnzKo/giphy.gif','https://media.giphy.com/media/5xtDarIN81U0KvlnzKo/giphy.gif','https://media.giphy.com/media/5xtDarIN81U0KvlnzKo/giphy_s.gif','https://media.giphy.com/media/5xtDarIN81U0KvlnzKo/giphy_s.gif',ARRAY['skating','trick','skateboard','cool','flip'],'Sports','Cool','public','approved','curated',true,true),
  ('Surfing Barrel','https://media.giphy.com/media/rcOlpTCkM1GAE/giphy.gif','https://media.giphy.com/media/rcOlpTCkM1GAE/giphy.gif','https://media.giphy.com/media/rcOlpTCkM1GAE/giphy_s.gif','https://media.giphy.com/media/rcOlpTCkM1GAE/giphy_s.gif',ARRAY['surfing','wave','ocean','chill','barrel'],'Sports','Cool','public','approved','curated',true,true),
  ('Three Pointer','https://media.giphy.com/media/l46Cgctdy5C23iB0c/giphy.gif','https://media.giphy.com/media/l46Cgctdy5C23iB0c/giphy.gif','https://media.giphy.com/media/l46Cgctdy5C23iB0c/giphy_s.gif','https://media.giphy.com/media/l46Cgctdy5C23iB0c/giphy_s.gif',ARRAY['basketball','three pointer','nba','swish','curry'],'Sports','Hype','public','approved','curated',true,true),

  -- =====================================================
  -- MUSIC (30 GIFs)
  -- =====================================================
  ('Headphones Vibe','https://media.giphy.com/media/tqfS3mgQU28ko/giphy.gif','https://media.giphy.com/media/tqfS3mgQU28ko/giphy.gif','https://media.giphy.com/media/tqfS3mgQU28ko/giphy_s.gif','https://media.giphy.com/media/tqfS3mgQU28ko/giphy_s.gif',ARRAY['music','headphones','vibe','chill','listen'],'Music','Cool','public','approved','curated',true,true),
  ('DJ Spinning','https://media.giphy.com/media/l378p60yRSCeVoyAM/giphy.gif','https://media.giphy.com/media/l378p60yRSCeVoyAM/giphy.gif','https://media.giphy.com/media/l378p60yRSCeVoyAM/giphy_s.gif','https://media.giphy.com/media/l378p60yRSCeVoyAM/giphy_s.gif',ARRAY['dj','music','party','spin','turntable'],'Music','Hype','public','approved','curated',true,true),
  ('Singing Along','https://media.giphy.com/media/4oMoIbIQrvCjm/giphy.gif','https://media.giphy.com/media/4oMoIbIQrvCjm/giphy.gif','https://media.giphy.com/media/4oMoIbIQrvCjm/giphy_s.gif','https://media.giphy.com/media/4oMoIbIQrvCjm/giphy_s.gif',ARRAY['singing','music','car','karaoke','feeling it'],'Music','Lit','public','approved','curated',true,true),
  ('Beat Drop','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy.gif','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy.gif','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy_s.gif','https://media.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy_s.gif',ARRAY['beat','drop','explosion','hype','bass'],'Music','Hype','public','approved','curated',true,true),
  ('Lo-Fi Chill','https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif','https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif','https://media.giphy.com/media/13HgwGsXF0aiGY/giphy_s.gif','https://media.giphy.com/media/13HgwGsXF0aiGY/giphy_s.gif',ARRAY['lofi','chill','study','relax','anime'],'Music','Cool','public','approved','curated',true,true),
  ('Disco Ball','https://media.giphy.com/media/xTiTnoHt2NwerFMsCI/giphy.gif','https://media.giphy.com/media/xTiTnoHt2NwerFMsCI/giphy.gif','https://media.giphy.com/media/xTiTnoHt2NwerFMsCI/giphy_s.gif','https://media.giphy.com/media/xTiTnoHt2NwerFMsCI/giphy_s.gif',ARRAY['disco','party','dance','sparkle','lights'],'Music','Lit','public','approved','curated',true,true),
  ('Bass Drop','https://media.giphy.com/media/l4FGpP4lxGGgK5CBW/giphy.gif','https://media.giphy.com/media/l4FGpP4lxGGgK5CBW/giphy.gif','https://media.giphy.com/media/l4FGpP4lxGGgK5CBW/giphy_s.gif','https://media.giphy.com/media/l4FGpP4lxGGgK5CBW/giphy_s.gif',ARRAY['bass','drop','dubstep','hype','edm'],'Music','Hype','public','approved','curated',true,true),
  ('Saxophone','https://media.giphy.com/media/kYBStwgFSLeJq/giphy.gif','https://media.giphy.com/media/kYBStwgFSLeJq/giphy.gif','https://media.giphy.com/media/kYBStwgFSLeJq/giphy_s.gif','https://media.giphy.com/media/kYBStwgFSLeJq/giphy_s.gif',ARRAY['sax','jazz','smooth','epic','music'],'Music','Cool','public','approved','curated',true,true),
  ('Dance Floor','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy_s.gif','https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy_s.gif',ARRAY['dance','party','club','lights','floor'],'Music','Lit','public','approved','curated',true,true),
  ('Mic Check','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy.gif','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy.gif','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy_s.gif','https://media.giphy.com/media/l0HlQ7LRalQqdWfao/giphy_s.gif',ARRAY['mic','rap','hiphop','check','perform'],'Music','Hype','public','approved','curated',true,true),
  ('Guitar Solo','https://media.giphy.com/media/l0IyjDnhpXmGF5RYs/giphy.gif','https://media.giphy.com/media/l0IyjDnhpXmGF5RYs/giphy.gif','https://media.giphy.com/media/l0IyjDnhpXmGF5RYs/giphy_s.gif','https://media.giphy.com/media/l0IyjDnhpXmGF5RYs/giphy_s.gif',ARRAY['guitar','solo','rock','shred','epic'],'Music','Lit','public','approved','curated',true,true),
  ('Piano Keys','https://media.giphy.com/media/l3vR4X3z65cnIJjCw/giphy.gif','https://media.giphy.com/media/l3vR4X3z65cnIJjCw/giphy.gif','https://media.giphy.com/media/l3vR4X3z65cnIJjCw/giphy_s.gif','https://media.giphy.com/media/l3vR4X3z65cnIJjCw/giphy_s.gif',ARRAY['piano','keys','classical','elegant','music'],'Music','Cool','public','approved','curated',true,true),

  -- =====================================================
  -- GAMING (25 GIFs)
  -- =====================================================
  ('Victory Royale','https://media.giphy.com/media/eKNrUbDJuFuaQ1A37p/giphy.gif','https://media.giphy.com/media/eKNrUbDJuFuaQ1A37p/giphy.gif','https://media.giphy.com/media/eKNrUbDJuFuaQ1A37p/giphy_s.gif','https://media.giphy.com/media/eKNrUbDJuFuaQ1A37p/giphy_s.gif',ARRAY['fortnite','victory','royale','win','gaming'],'Gaming','Hype','public','approved','curated',true,true),
  ('Minecraft Build','https://media.giphy.com/media/WpaVhEcp3Qo2TjwyI1/giphy.gif','https://media.giphy.com/media/WpaVhEcp3Qo2TjwyI1/giphy.gif','https://media.giphy.com/media/WpaVhEcp3Qo2TjwyI1/giphy_s.gif','https://media.giphy.com/media/WpaVhEcp3Qo2TjwyI1/giphy_s.gif',ARRAY['minecraft','build','gaming','creative','blocks'],'Gaming','Cool','public','approved','curated',true,true),
  ('Pokemon Battle','https://media.giphy.com/media/xuXzcHMkuwvf2/giphy.gif','https://media.giphy.com/media/xuXzcHMkuwvf2/giphy.gif','https://media.giphy.com/media/xuXzcHMkuwvf2/giphy_s.gif','https://media.giphy.com/media/xuXzcHMkuwvf2/giphy_s.gif',ARRAY['pokemon','battle','pikachu','gamer','nostalgia'],'Gaming','Hype','public','approved','curated',true,true),
  ('Among Us Sus','https://media.giphy.com/media/RtdRhc7TxBxB0YAsK6/giphy.gif','https://media.giphy.com/media/RtdRhc7TxBxB0YAsK6/giphy.gif','https://media.giphy.com/media/RtdRhc7TxBxB0YAsK6/giphy_s.gif','https://media.giphy.com/media/RtdRhc7TxBxB0YAsK6/giphy_s.gif',ARRAY['among us','sus','imposter','gaming','meme'],'Gaming','Side Eye','public','approved','curated',true,true),
  ('Zelda Sword','https://media.giphy.com/media/fwoOoDZpEpdQewQdRR/giphy.gif','https://media.giphy.com/media/fwoOoDZpEpdQewQdRR/giphy.gif','https://media.giphy.com/media/fwoOoDZpEpdQewQdRR/giphy_s.gif','https://media.giphy.com/media/fwoOoDZpEpdQewQdRR/giphy_s.gif',ARRAY['zelda','link','sword','nintendo','classic'],'Gaming','Cool','public','approved','curated',true,true),
  ('Controller Rage','https://media.giphy.com/media/3ohc0VmrLRmy5om1q0/giphy.gif','https://media.giphy.com/media/3ohc0VmrLRmy5om1q0/giphy.gif','https://media.giphy.com/media/3ohc0VmrLRmy5om1q0/giphy_s.gif','https://media.giphy.com/media/3ohc0VmrLRmy5om1q0/giphy_s.gif',ARRAY['rage','controller','gaming','angry','tilted'],'Gaming','Side Eye','public','approved','curated',true,true),
  ('Level Up','https://media.giphy.com/media/dxn6fRlTIShoeBr69N/giphy.gif','https://media.giphy.com/media/dxn6fRlTIShoeBr69N/giphy.gif','https://media.giphy.com/media/dxn6fRlTIShoeBr69N/giphy_s.gif','https://media.giphy.com/media/dxn6fRlTIShoeBr69N/giphy_s.gif',ARRAY['level up','gaming','progress','win','upgrade'],'Gaming','Hype','public','approved','curated',true,true),
  ('GG Easy','https://media.giphy.com/media/KEYEpIngcmXlHetDqz/giphy.gif','https://media.giphy.com/media/KEYEpIngcmXlHetDqz/giphy.gif','https://media.giphy.com/media/KEYEpIngcmXlHetDqz/giphy_s.gif','https://media.giphy.com/media/KEYEpIngcmXlHetDqz/giphy_s.gif',ARRAY['gg','easy','gaming','win','esports'],'Gaming','Cool','public','approved','curated',true,true),
  ('Speedrun','https://media.giphy.com/media/3oEduXdm2RKlF1XaOI/giphy.gif','https://media.giphy.com/media/3oEduXdm2RKlF1XaOI/giphy.gif','https://media.giphy.com/media/3oEduXdm2RKlF1XaOI/giphy_s.gif','https://media.giphy.com/media/3oEduXdm2RKlF1XaOI/giphy_s.gif',ARRAY['speedrun','gaming','fast','record','twitch'],'Gaming','Hype','public','approved','curated',true,true),

  -- =====================================================
  -- TRENDING / NEW (35 GIFs)
  -- =====================================================
  ('Good Vibes','https://media.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy.gif','https://media.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy.gif','https://media.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy_s.gif','https://media.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy_s.gif',ARRAY['good vibes','neon','mood','blue','aesthetic'],'New','Lit','public','approved','curated',true,true),
  ('Fresh Drop','https://media.giphy.com/media/3ohs7KViF6rA4aan5u/giphy.gif','https://media.giphy.com/media/3ohs7KViF6rA4aan5u/giphy.gif','https://media.giphy.com/media/3ohs7KViF6rA4aan5u/giphy_s.gif','https://media.giphy.com/media/3ohs7KViF6rA4aan5u/giphy_s.gif',ARRAY['fresh','new','drop','latest','release'],'New','Cool','public','approved','curated',true,true),
  ('Hot Take','https://media.giphy.com/media/l0IyajjbNiRvCr7RC/giphy.gif','https://media.giphy.com/media/l0IyajjbNiRvCr7RC/giphy.gif','https://media.giphy.com/media/l0IyajjbNiRvCr7RC/giphy_s.gif','https://media.giphy.com/media/l0IyajjbNiRvCr7RC/giphy_s.gif',ARRAY['hot','take','opinion','fire','controversial'],'New','Lit','public','approved','curated',true,true),
  ('Vaporwave','https://media.giphy.com/media/xT9DPJVjlYHwWsZRxm/giphy.gif','https://media.giphy.com/media/xT9DPJVjlYHwWsZRxm/giphy.gif','https://media.giphy.com/media/xT9DPJVjlYHwWsZRxm/giphy_s.gif','https://media.giphy.com/media/xT9DPJVjlYHwWsZRxm/giphy_s.gif',ARRAY['vaporwave','aesthetic','retro','vibes','art'],'New','Cool','public','approved','curated',true,true),
  ('Retrowave','https://media.giphy.com/media/l0HlBO7eyXzSZkJri/giphy.gif','https://media.giphy.com/media/l0HlBO7eyXzSZkJri/giphy.gif','https://media.giphy.com/media/l0HlBO7eyXzSZkJri/giphy_s.gif','https://media.giphy.com/media/l0HlBO7eyXzSZkJri/giphy_s.gif',ARRAY['retrowave','80s','sunset','vibe','synth'],'New','Cool','public','approved','curated',true,true),
  ('Future Tech','https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy.gif','https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy.gif','https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy_s.gif','https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy_s.gif',ARRAY['future','tech','hologram','sci-fi','digital'],'New','Wow','public','approved','curated',true,true),
  ('Glitch Art','https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif','https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif','https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy_s.gif','https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy_s.gif',ARRAY['glitch','art','digital','trippy','aesthetic'],'New','Cool','public','approved','curated',true,true),
  ('Neon City','https://media.giphy.com/media/xT9IgjJDNKiJgCJDdC/giphy.gif','https://media.giphy.com/media/xT9IgjJDNKiJgCJDdC/giphy.gif','https://media.giphy.com/media/xT9IgjJDNKiJgCJDdC/giphy_s.gif','https://media.giphy.com/media/xT9IgjJDNKiJgCJDdC/giphy_s.gif',ARRAY['neon','city','night','aesthetic','cyber'],'New','Lit','public','approved','curated',true,true),
  ('Viral Moment','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy_s.gif','https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy_s.gif',ARRAY['viral','trending','internet','famous','moment'],'New','Hype','public','approved','curated',true,true),
  ('Electric Slide','https://media.giphy.com/media/3o6Zt6ML6BLzEhEBFC/giphy.gif','https://media.giphy.com/media/3o6Zt6ML6BLzEhEBFC/giphy.gif','https://media.giphy.com/media/3o6Zt6ML6BLzEhEBFC/giphy_s.gif','https://media.giphy.com/media/3o6Zt6ML6BLzEhEBFC/giphy_s.gif',ARRAY['electric','slide','dance','retro','party'],'New','Hype','public','approved','curated',true,true),

  -- =====================================================
  -- CLIPS / AESTHETIC (25 GIFs)
  -- =====================================================
  ('Night Drive','https://media.giphy.com/media/l2SpQdJ7u7rfgED5e/giphy.gif','https://media.giphy.com/media/l2SpQdJ7u7rfgED5e/giphy.gif','https://media.giphy.com/media/l2SpQdJ7u7rfgED5e/giphy_s.gif','https://media.giphy.com/media/l2SpQdJ7u7rfgED5e/giphy_s.gif',ARRAY['drive','night','city','vibes','road'],'Clips','Cool','public','approved','curated',true,true),
  ('City Lights','https://media.giphy.com/media/1BdJd24oEwvuSvXYb0/giphy.gif','https://media.giphy.com/media/1BdJd24oEwvuSvXYb0/giphy.gif','https://media.giphy.com/media/1BdJd24oEwvuSvXYb0/giphy_s.gif','https://media.giphy.com/media/1BdJd24oEwvuSvXYb0/giphy_s.gif',ARRAY['city','lights','night','aesthetic','skyline'],'Clips','Cool','public','approved','curated',true,true),
  ('Rain Window','https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy.gif','https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy.gif','https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy_s.gif','https://media.giphy.com/media/t7Qb8655Z1VfBGr5XB/giphy_s.gif',ARRAY['rain','window','cozy','mood','storm'],'Clips','Cool','public','approved','curated',true,true),
  ('Mountain View','https://media.giphy.com/media/xUOxeZn47mrdabqDNC/giphy.gif','https://media.giphy.com/media/xUOxeZn47mrdabqDNC/giphy.gif','https://media.giphy.com/media/xUOxeZn47mrdabqDNC/giphy_s.gif','https://media.giphy.com/media/xUOxeZn47mrdabqDNC/giphy_s.gif',ARRAY['mountain','nature','scenic','peaceful','hike'],'Clips','Cool','public','approved','curated',true,true),
  ('Coffee Pour','https://media.giphy.com/media/xUOrw5LIxb8S9X1LGg/giphy.gif','https://media.giphy.com/media/xUOrw5LIxb8S9X1LGg/giphy.gif','https://media.giphy.com/media/xUOrw5LIxb8S9X1LGg/giphy_s.gif','https://media.giphy.com/media/xUOrw5LIxb8S9X1LGg/giphy_s.gif',ARRAY['coffee','morning','pour','aesthetic','latte'],'Clips','Cool','public','approved','curated',true,true),
  ('Fireplace','https://media.giphy.com/media/l0ExsgrTuACbtPaqQ/giphy.gif','https://media.giphy.com/media/l0ExsgrTuACbtPaqQ/giphy.gif','https://media.giphy.com/media/l0ExsgrTuACbtPaqQ/giphy_s.gif','https://media.giphy.com/media/l0ExsgrTuACbtPaqQ/giphy_s.gif',ARRAY['fire','cozy','warm','relax','winter'],'Clips','Cool','public','approved','curated',true,true),
  ('Ocean Waves','https://media.giphy.com/media/xT1XGLm7CJknNZKVS8/giphy.gif','https://media.giphy.com/media/xT1XGLm7CJknNZKVS8/giphy.gif','https://media.giphy.com/media/xT1XGLm7CJknNZKVS8/giphy_s.gif','https://media.giphy.com/media/xT1XGLm7CJknNZKVS8/giphy_s.gif',ARRAY['ocean','waves','beach','relax','blue'],'Clips','Cool','public','approved','curated',true,true),
  ('Neon Street','https://media.giphy.com/media/l378khQxt68syiWJy/giphy.gif','https://media.giphy.com/media/l378khQxt68syiWJy/giphy.gif','https://media.giphy.com/media/l378khQxt68syiWJy/giphy_s.gif','https://media.giphy.com/media/l378khQxt68syiWJy/giphy_s.gif',ARRAY['neon','street','night','city','cyberpunk'],'Clips','Cool','public','approved','curated',true,true),
  ('Tokyo Night','https://media.giphy.com/media/4ilFRqgbzbx4c/giphy.gif','https://media.giphy.com/media/4ilFRqgbzbx4c/giphy.gif','https://media.giphy.com/media/4ilFRqgbzbx4c/giphy_s.gif','https://media.giphy.com/media/4ilFRqgbzbx4c/giphy_s.gif',ARRAY['tokyo','japan','night','city','lights'],'Clips','Cool','public','approved','curated',true,true),
  ('Lightning Storm','https://media.giphy.com/media/l0MYLePFMI1m69fpu/giphy.gif','https://media.giphy.com/media/l0MYLePFMI1m69fpu/giphy.gif','https://media.giphy.com/media/l0MYLePFMI1m69fpu/giphy_s.gif','https://media.giphy.com/media/l0MYLePFMI1m69fpu/giphy_s.gif',ARRAY['lightning','storm','power','nature','dramatic'],'Clips','Wow','public','approved','curated',true,true),
  ('Space Journey','https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy.gif','https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy.gif','https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy_s.gif','https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy_s.gif',ARRAY['space','stars','galaxy','journey','universe'],'Clips','Wow','public','approved','curated',true,true),
  ('Aurora Borealis','https://media.giphy.com/media/xT39D8FIJHDgBLKHXa/giphy.gif','https://media.giphy.com/media/xT39D8FIJHDgBLKHXa/giphy.gif','https://media.giphy.com/media/xT39D8FIJHDgBLKHXa/giphy_s.gif','https://media.giphy.com/media/xT39D8FIJHDgBLKHXa/giphy_s.gif',ARRAY['aurora','borealis','northern lights','nature','beautiful'],'Clips','Wow','public','approved','curated',true,true),
  ('Waterfall','https://media.giphy.com/media/xT5LMESsx1kUe8Hiyk/giphy.gif','https://media.giphy.com/media/xT5LMESsx1kUe8Hiyk/giphy.gif','https://media.giphy.com/media/xT5LMESsx1kUe8Hiyk/giphy_s.gif','https://media.giphy.com/media/xT5LMESsx1kUe8Hiyk/giphy_s.gif',ARRAY['waterfall','nature','water','scenic','peaceful'],'Clips','Wow','public','approved','curated',true,true);

  RAISE NOTICE 'FWD curated GIF seed complete — % GIFs inserted.', (SELECT COUNT(*) FROM public.fwd_gifs WHERE owner_user_id IS NULL);
END $$;
